import {useQuery} from '@tanstack/react-query';
import {monitoringResponseSchema,type MonitoringResponse} from '../../../../../packages/contracts/src/monitoring';
import type {Owner,Scope} from '../../../../../packages/contracts/src/index';
import type {Client} from '../../lib/firebase';
import type {Locale} from '../../lib/i18n';
import {Button} from '../../components/button';
const words={vi:{title:'Lịch sử theo dõi tự động',loaded:'Tải lúc',services:'Dịch vụ',loading:'Đang tải lịch sử…',error:'Chưa tải được lịch sử theo dõi.',retry:'Thử lại',empty:'Chưa có lần theo dõi.',noHistory:'Chưa có lần thành công trong phần lịch sử được tải của khoảng này.',recent:'Lịch sử gần đây trong khoảng đã chọn; chưa phải toàn bộ lịch sử.',truncated:'Một phần lịch sử chưa được tải.',latestScope:'Lần thử này ngoài khoảng đang chọn.',available:'Có dữ liệu',partial:'Dữ liệu chưa đầy đủ',emptySource:'Chưa ghi nhận dữ liệu',not_configured:'Chưa kết nối',permission_denied:'Thiếu quyền đọc',failed:'Nguồn chưa phản hồi',latest:'Lần thử gần nhất',history:'Các lần thành công',source:'Nguồn',window:'Khoảng dữ liệu',checked:'Lần thử',success:'Lần thành công',through:'Dữ liệu thành công đến',attempted:'Đã thử đọc đến',stale:'Dữ liệu thành công gần nhất đã hơn 30 phút.',requests:'Lượt gọi',errors:'HTTP 5xx',rate:'Tỷ lệ HTTP 5xx',unknown:'Chưa có',fixture:'Dữ liệu kiểm thử trên emulator.'},en:{title:'Automatic monitoring history',loaded:'Loaded at',services:'Services',loading:'Loading history…',error:'Monitoring history could not be loaded.',retry:'Retry',empty:'No monitoring attempts recorded.',noHistory:'No successful attempts in the loaded history for this period.',recent:'Recent history in the selected period; this is not the full history.',truncated:'Some history has not been loaded.',latestScope:'This attempt is outside the selected period.',available:'Data available',partial:'Incomplete data',emptySource:'No observations',not_configured:'Not connected',permission_denied:'Read permission needed',failed:'Source unavailable',latest:'Latest attempt',history:'Successful attempts',source:'Source',window:'Data window',checked:'Last attempt',success:'Last success',through:'Successful data through',attempted:'Attempted through',stale:'The latest successful data is over 30 minutes old.',requests:'Requests',errors:'HTTP 5xx',rate:'HTTP 5xx rate',unknown:'Not yet available',fixture:'Emulator test data.'}};
type Props={client:Client;owner:Owner;scope:Scope;locale:Locale;appNames?:Record<string,string>};
export function MonitoringHistory({client,owner,scope,locale,appNames={}}:Props){
 const enabled=client.config.emulator||client.config.monitoringEnabled;
 const t=words[locale];
 const query=useQuery({enabled,queryKey:['monitoring-history',owner.uid,scope],queryFn:async()=>monitoringResponseSchema.parse(await client.call('listMonitoringSnapshots',{scope,limit:5})),retry:false,staleTime:60000});
 const snapshot=query.data;
 if(!enabled)return null;
 const date=(value:string|null)=>value?new Intl.DateTimeFormat(locale,{timeZone:scope.timezone,dateStyle:'short',timeStyle:'short'}).format(new Date(value)):t.unknown;
 const status=(value:MonitoringResponse['data'][number]['status'])=>value==='empty'?t.emptySource:t[value];
 const report=(value:NonNullable<MonitoringResponse['data'][number]['latestAttempt']>,appId:string)=>{
  const row=value.data.find(item=>item.appId===appId);if(!row)return null;
  return <article key={value.id} className="incident-form"><p>{t.window}: {date(value.scope.from)} – {date(value.scope.to)} · {scope.timezone}</p><p>{t.source}: {row.provenance.provider} · {row.provenance.resourceRef??t.unknown}</p><p>{t.services}: {row.services.length?row.services.join(', '):t.unknown}</p><p>{status(row.metrics.status)} · {date(value.createdAt)}</p><div className="metrics"><section><span>{t.requests}</span><strong>{row.metrics.requestCount?.toLocaleString(locale)??'—'}</strong></section><section><span>{t.errors}</span><strong>{row.metrics.serverErrorCount?.toLocaleString(locale)??'—'}</strong></section><section><span>{t.rate}</span><strong>{row.metrics.errorRate===null?'—':new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:2}).format(row.metrics.errorRate)}</strong></section></div></article>;
 };
 return <section className="registry operation-section" aria-label={t.title} data-testid="monitoring-history"><div className="section-heading"><h2>{t.title}</h2></div>{query.isPending&&<p role="status">{t.loading}</p>}{query.isError&&<div role="alert"><p>{t.error}</p><Button onClick={()=>void query.refetch()}>{t.retry}</Button></div>}{snapshot&&<><p className="footnote">{t.loaded}: {date(snapshot.meta.fetchedAt)} · {scope.timezone}</p>{snapshot.meta.historyTruncated&&<p role="status">{t.truncated}</p>}{snapshot.meta.fixture&&!client.config.emulator&&<p className="footnote">{t.fixture}</p>}{!snapshot.data.length&&<p className="empty">{t.empty}</p>}{snapshot.data.map(item=>{
 const outsideScope=item.latestAttempt!==null&&(Date.parse(item.latestAttempt.scope.from)<Date.parse(scope.from)||Date.parse(item.latestAttempt.scope.to)>Date.parse(scope.to));
 const stale=item.lastSuccessfulThrough!==null&&Date.parse(snapshot.meta.fetchedAt)-Date.parse(item.lastSuccessfulThrough)>30*60000;
 return <section key={item.appId} className="operation-section" aria-label={appNames[item.appId]??item.appId}><div className="section-heading"><h3>{appNames[item.appId]??item.appId}</h3><span className="status">{status(item.status)}</span></div>{(item.lastAttemptAt||item.attemptedThrough)&&<p className="footnote">{item.lastAttemptAt&&<>{t.checked}: {date(item.lastAttemptAt)}</>}{item.lastAttemptAt&&item.attemptedThrough&&' · '}{item.attemptedThrough&&<>{t.attempted}: {date(item.attemptedThrough)}</>}</p>}{(item.lastSuccessAt||item.lastSuccessfulThrough)&&<p className="footnote">{item.lastSuccessAt&&<>{t.success}: {date(item.lastSuccessAt)}</>}{item.lastSuccessAt&&item.lastSuccessfulThrough&&' · '}{item.lastSuccessfulThrough&&<>{t.through}: {date(item.lastSuccessfulThrough)}</>}</p>}{stale&&<p role="status">{t.stale}</p>}{item.latestAttempt?<details open><summary>{t.latest}</summary>{outsideScope&&<p className="footnote">{t.latestScope}</p>}{report(item.latestAttempt,item.appId)}</details>:<p className="empty">{t.empty}</p>}{item.latestAttempt&&!item.history.length&&<p className="empty">{t.noHistory}</p>}{item.history.length>0&&<details><summary>{t.history} · {item.history.length}</summary><p className="footnote">{t.recent}</p>{item.history.map(value=>report(value,item.appId))}</details>}</section>;
 })}</>}</section>;
}
