import {useState} from 'react';
import {useInfiniteQuery,useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {NavLink} from 'react-router-dom';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip} from 'recharts';
import {APP_CATALOG,type Owner,type Scope} from '../../../../../packages/contracts/src/index';
import {operationsResponseSchema} from '../../../../../packages/contracts/src/metrics';
import {incidentPageSchema,notificationPageSchema,transitions,type Incident} from '../../../../../packages/contracts/src/operations';
import type {Client} from '../../lib/firebase';
import type {Locale} from '../../lib/i18n';
import {Button} from '../../components/button';
const words={vi:{loading:'Đang tải…',retry:'Thử lại',failed:'Chưa tải được dữ liệu.',empty:'Không có kết quả trong khoảng này.',more:'Xem thêm',request:'Lượt gọi',errors:'HTTP 5xx',rate:'Tỷ lệ HTTP 5xx',logs:'Nhật ký',source:'Nguồn',available:'Có dữ liệu',partial:'Dữ liệu chưa đầy đủ',not_configured:'Chưa kết nối',permission_denied:'Thiếu quyền đọc',failedSource:'Nguồn chưa phản hồi',emptySource:'Chưa ghi nhận dữ liệu',workflow:'Xử lý',signal:'Tín hiệu nguồn',firing:'Đang lỗi',recovered:'Đã hồi phục',open:'Mới',acknowledged:'Đã nhận',investigating:'Đang kiểm tra',mitigated:'Đã giảm ảnh hưởng',resolved:'Đã xử lý',note:'Ghi chú',save:'Lưu xử lý',read:'Đánh dấu đã đọc',readDone:'Đã đọc',cancel:'Hủy',conflict:'Chưa lưu được. Làm mới để kiểm tra trạng thái rồi thử lại.',metadata:'Chỉ tải thời gian, mức độ và mã HTTP.',at:'Thời gian',service:'Dịch vụ',severity:'Mức độ',status:'HTTP',viewIncident:'Xem sự cố'},en:{loading:'Loading…',retry:'Retry',failed:'Data could not be loaded.',empty:'No results in this period.',more:'Load more',request:'Requests',errors:'HTTP 5xx',rate:'HTTP 5xx rate',logs:'Logs',source:'Source',available:'Data available',partial:'Incomplete data',not_configured:'Not connected',permission_denied:'Read permission needed',failedSource:'Source unavailable',emptySource:'No observations',workflow:'Workflow',signal:'Source signal',firing:'Firing',recovered:'Recovered',open:'Open',acknowledged:'Acknowledged',investigating:'Investigating',mitigated:'Mitigated',resolved:'Resolved',note:'Note',save:'Save workflow',read:'Mark as read',readDone:'Read',cancel:'Cancel',conflict:'Changes were not saved. Refresh to check the current state, then retry.',metadata:'Metadata only; log content and personal data are not fetched.',at:'Time',service:'Service',severity:'Severity',status:'HTTP',viewIncident:'View incident'}};
type Props={appNames?:Record<string,string>;client:Client;owner:Owner;scope:Scope;locale:Locale;onNotice:(text:string,kind:'info'|'error',pending?:boolean)=>void};
const appName=(id:string,names:Record<string,string>={})=>names[id]??APP_CATALOG.find(app=>app.id===id)?.name??id;
export function OperationsPage({client,owner,scope,locale,appNames}:Props){
 const t=words[locale];const [logCursor,setLogCursor]=useState<string|null>(null);
 const query=useQuery({queryKey:['operations',owner.uid,scope,logCursor],queryFn:async()=>operationsResponseSchema.parse(await client.call('getOperations',{scope,logCursor})),retry:false,staleTime:60000});
 const label=(status:string)=>status==='failed'?t.failedSource:status==='empty'?t.emptySource:t[status as 'available'];
 const format=(value:string)=>new Intl.DateTimeFormat(locale,{timeZone:scope.timezone,dateStyle:'short',timeStyle:'short'}).format(new Date(value));
 if(query.isPending)return <p role="status">{t.loading}</p>;
 if(query.isError)return <div role="alert"><p>{t.failed}</p><Button onClick={()=>void query.refetch()}>{t.retry}</Button></div>;
 return <div className="operation-sections">{query.data.data.map(item=><section className="registry operation-section" key={item.appId}><div className="section-heading"><h2>{appName(item.appId,appNames)}</h2><span className="status">{label(item.metrics.status)}</span></div>
  <div className="metrics"><section><span>{t.request}</span><strong>{item.metrics.requestCount?.toLocaleString(locale)??'—'}</strong></section><section><span>{t.errors}</span><strong>{item.metrics.serverErrorCount?.toLocaleString(locale)??'—'}</strong></section><section><span>{t.rate}</span><strong>{item.metrics.errorRate===null?'—':new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:2}).format(item.metrics.errorRate)}</strong></section></div>
  {item.metrics.points.length>0&&<><div className="metric-chart" role="img" aria-label={`${appName(item.appId,appNames)} · ${t.request} / ${t.errors}`}><ResponsiveContainer width="100%" height={200}><LineChart data={item.metrics.points.flatMap((point,index,points)=>{const next=points[index+1];return next&&Date.parse(next.at)-Date.parse(point.at)>3600000?[point,{at:new Date(Date.parse(point.at)+3600000).toISOString(),requests:null,errors:null}]:[point];})}><XAxis dataKey="at" tickFormatter={value=>format(String(value))} minTickGap={80}/><YAxis/><Tooltip labelFormatter={value=>format(String(value))}/><Line dataKey="requests" name={t.request} stroke="#163cff" dot={false}/><Line dataKey="errors" name={t.errors} stroke="#bd3030" dot={false}/></LineChart></ResponsiveContainer></div><details><summary>{t.request} / {t.errors}</summary><div className="table-scroll"><table><thead><tr><th>{t.at}</th><th>{t.request}</th><th>{t.errors}</th></tr></thead><tbody>{item.metrics.points.map(p=><tr key={p.at}><td>{format(p.at)}</td><td>{p.requests.toLocaleString(locale)}</td><td>{p.errors.toLocaleString(locale)}</td></tr>)}</tbody></table></div></details></>}
  <div className="section-heading"><h3>{t.logs}</h3><span className="status">{label(item.logs.status)}</span></div><p className="footnote">{t.metadata}</p>
  {item.logs.entries.length>0&&<div className="table-scroll"><table><thead><tr><th>{t.at}</th><th>{t.service}</th><th>{t.severity}</th><th>{t.status}</th></tr></thead><tbody>{item.logs.entries.map((entry,i)=><tr key={`${entry.at}:${i}`}><td>{format(entry.at)}</td><td>{entry.service}</td><td>{entry.severity}</td><td>{entry.httpStatus??'—'}</td></tr>)}</tbody></table></div>}
  {item.logs.nextCursor&&scope.appId!=='all'&&<Button onClick={()=>setLogCursor(item.logs.nextCursor)}>{t.more}</Button>}
  <details><summary>{t.source}</summary><p>{item.provenance.resourceRef??t.not_configured} · {format(item.freshness.fetchedAt)}</p><p>{item.services.join(', ')}</p></details>
 </section>)}</div>;
}
export function IncidentsPage({client,owner,scope,locale,onNotice,appNames}:Props){
 const t=words[locale];const cache=useQueryClient();const [selected,setSelected]=useState<Incident|null>(null);const [note,setNote]=useState('');const [workflow,setWorkflow]=useState('');
 const query=useInfiniteQuery({queryKey:['incidents',owner.uid,scope],initialPageParam:null as string|null,queryFn:async({pageParam})=>incidentPageSchema.parse(await client.call('listIncidents',{scope,cursor:pageParam})),getNextPageParam:last=>last.nextCursor??undefined,retry:false});
 const mutation=useMutation({mutationFn:async()=>{if(!selected)throw Error();return client.call('updateIncident',{id:selected.id,revision:selected.revision,workflow,note,idempotencyKey:crypto.randomUUID()});},onMutate:()=>onNotice(t.loading,'info',true),onSuccess:async()=>{setSelected(null);setNote('');onNotice(locale==='vi'?'Đã lưu xử lý.':'Workflow saved.','info');await cache.invalidateQueries({queryKey:['incidents',owner.uid]});},onError:()=>onNotice(t.conflict,'error')});
 const items=query.data?.pages.flatMap(page=>page.data)??[];
 return <section className="registry">{query.isPending&&<p role="status">{t.loading}</p>}{query.isError&&<p role="alert">{t.failed}<Button onClick={()=>void query.refetch()}>{t.retry}</Button></p>}{!query.isPending&&!query.isError&&!items.length&&<p className="empty">{t.empty}</p>}
 {items.map(item=><article className="incident-row" key={item.id}><div><h3>{item.title}</h3><p>{appName(item.appId,appNames)} · {item.severity}</p><p>{t.signal}: {t[item.sourceState]} · {t.workflow}: {t[item.workflow]}</p><time dateTime={item.updatedAt}>{new Intl.DateTimeFormat(locale,{timeZone:scope.timezone,dateStyle:'short',timeStyle:'short'}).format(new Date(item.updatedAt))}</time></div><Button disabled={mutation.isPending} onClick={()=>{setSelected(item);setWorkflow(transitions[item.workflow][0]!);setNote('');}}>{t.workflow}</Button></article>)}
 {selected&&<form className="incident-form" onSubmit={event=>{event.preventDefault();mutation.mutate();}}><h3>{selected.title}</h3><label>{t.workflow}<select value={workflow} onChange={event=>setWorkflow(event.target.value)}>{transitions[selected.workflow].map(value=><option key={value} value={value}>{t[value]}</option>)}</select></label><label>{t.note}<textarea required maxLength={1000} value={note} onChange={event=>setNote(event.target.value)}/></label><div><Button type="submit" disabled={mutation.isPending||!note.trim()}>{t.save}</Button><Button type="button" disabled={mutation.isPending} onClick={()=>setSelected(null)}>{t.cancel}</Button></div></form>}
 {query.hasNextPage&&<Button disabled={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>{t.more}</Button>}
 </section>;
}
export function NotificationsPage({client,owner,scope,locale,onNotice,appNames}:Props){
 const t=words[locale];const cache=useQueryClient();
 const query=useInfiniteQuery({queryKey:['notifications',owner.uid,scope],initialPageParam:null as string|null,queryFn:async({pageParam})=>notificationPageSchema.parse(await client.call('listNotifications',{scope,cursor:pageParam})),getNextPageParam:last=>last.nextCursor??undefined,retry:false});
 const mutation=useMutation({mutationFn:(id:string)=>client.call('markNotificationRead',{id,read:true,idempotencyKey:crypto.randomUUID()}),onSuccess:async()=>{await cache.invalidateQueries({queryKey:['notifications',owner.uid]});},onError:()=>onNotice(t.conflict,'error')});
 const items=query.data?.pages.flatMap(page=>page.data)??[];
 return <section className="registry">{query.isPending&&<p role="status">{t.loading}</p>}{query.isError&&<p role="alert">{t.failed}<Button onClick={()=>void query.refetch()}>{t.retry}</Button></p>}{!query.isPending&&!query.isError&&!items.length&&<p className="empty">{t.empty}</p>}{items.map(item=><article className="incident-row" key={item.id}><div><h3>{item.title}</h3><p>{appName(item.appId,appNames)} · {item.severity}</p><NavLink to={`/incidents?${new URLSearchParams({app:item.appId,days:'30',timezone:scope.timezone})}`}>{t.viewIncident}</NavLink></div><Button disabled={item.read||mutation.isPending} onClick={()=>mutation.mutate(item.id)}>{item.read?t.readDone:t.read}</Button></article>)}{query.hasNextPage&&<Button disabled={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>{t.more}</Button>}</section>;
}
