import {createRequire} from 'node:module';
import {readFileSync,writeFileSync} from 'node:fs';
const require=createRequire(import.meta.url);
const {requireAuth}=require('firebase-tools/lib/requireAuth');
const {getGlobalDefaultAccount}=require('firebase-tools/lib/auth');
const {Client}=require('firebase-tools/lib/apiv2');
const project=process.env.SM_VERIFY_PROJECT ?? 'satsunicmanager';
if (!['satsunicmanager'].includes(project)) throw new Error('Unapproved project');
if(!['SM-CLOUD-002-STEPS-1-2','SM-CLOUD-003'].includes(process.env.SM_CLOUD_APPROVAL) || (project==='satsunicmanager-staging' && process.env.SM_CLOUD_APPROVAL!=='SM-CLOUD-003')) throw new Error('Explicit approved setup invocation required');
const sdk=JSON.parse(readFileSync(project==='satsunicmanager'?'docs/evidence/firebase-public-sdk.json':'docs/evidence/staging-public-sdk.json','utf8'));
const appIds={'satsunicmanager':'1:317759361800:web:d4710116013ca2dca492bd','satsunicmanager-staging':'1:274705062317:web:5db2f6b528dc8e01656924'};
if(sdk.projectId!==project||sdk.appId!==appIds[project]||sdk.authDomain!==`${project}.firebaseapp.com`) throw new Error('Unexpected app');
await requireAuth({project,...getGlobalDefaultAccount()});
const client=new Client({urlPrefix:'https://identitytoolkit.googleapis.com/admin',apiVersion:'v2'});
const body={client:{permissions:{disabledUserSignup:true,disabledUserDeletion:true}},authorizedDomains:[sdk.authDomain,`${project}.web.app`]};
const response=await client.patch(`/projects/${project}/config`,body,{headers:{'x-goog-user-project':project},queryParams:{updateMask:'client.permissions.disabledUserSignup,client.permissions.disabledUserDeletion,authorizedDomains',fields:'name,subtype,client.permissions,authorizedDomains'},resolveOnHTTPError:true});
const report={projectId:project,completedAt:new Date().toISOString(),httpStatus:response.status,data:response.status<400?response.body:null,error:response.status>=400?{code:response.body?.error?.status,message:response.body?.error?.message}:null};
writeFileSync(`docs/evidence/${project}-auth-hardening.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
if(response.status>=400||response.body?.client?.permissions?.disabledUserSignup!==true) process.exitCode=1;
